services:
  backend:
    container_name: devops-analyzer-backend
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    working_dir: /app
    command: ["node", "src/index.js"]
    env_file:
      - .env
    restart: unless-stopped
