version: '3.8'
services:
  backend:
    container_name: devops-analyzer-backend
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    restart: unless-stopped
    volumes:
      - backend-data:/app/data

volumes:
  backend-data: