name: Run Tests

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name:  Vérif du code
        uses: actions/checkout@v3

      - name:  Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18  

      - name: Installer les dépendances
        run: npm install

      - name: Lancer les tests
        run: npm test
